### ISSUE TITLE
[Suggestion] Private Mode

### ISSUE THREAD

**Issue by NotAShelf** [Facinorous-420/dick#17]
A "private mode" that hides the **Total Files Saved**, **Total Space Used** and **Total Users** sections in the login page.

**Comment by NotAShelf** [comment]
this is a suggestion rather than a request, if it receives positive feedback I'd be more than happy to contribute it myself

**Comment by Facinorous-420** [comment]
This would be good to tackle at the same time -> #14 

since we will need a place to store this variable in DICK on system restarts :) 
This is a good suggestion overall, and if you dont get around to adding it I will def work on it eventually :D

**Comment by NotAShelf** [comment]
Great to hear! I will try to assist with #14 whenever I get the chance, and then I can try my luck with implementing this as a system.
Thank you for your feedback!
