### ISSUE TITLE
Is it possible to use with the docker version?

### ISSUE THREAD

**Issue by Traction6131** [Facinorous-420/dick#21]
yo, 
so I forked the repo to create a quick & dirty docker image, then realized how the software works. So I don't  know anything bout js, but it would be possible to have it run with docker whilst ass is also running on a _seperate_ container(since one would work, but, idk, not really docker-like). Or would I need to wait until there's an api?
thanks

**Comment by Facinorous-420** [comment]
> yo, so I forked the repo to create a quick & dirty docker image, then realized how the software works. So I don't know anything bout js, but it would be possible to have it run with docker whilst ass is also running on a _seperate_ container(since one would work, but, idk, not really docker-like). Or would I need to wait until there's an api? thanks

Youll be able to put your dick in docker soon, thanks for the suggestion

**Comment by Traction6131** [comment]
thanks, I'll try to be gentle.
