### ISSUE TITLE
Add theme colour to database

### ISSUE THREAD

**Issue by wdhdev** [Facinorous-420/dick#26]
Allow us to customise the different theme colours.

**Comment by Facinorous-420** [comment]
> Allow us to customise the different theme colours.

You can do this via this file currently: https://github.com/Facinorous-420/dick/blob/master/tailwind.config.js
Make sure to rebuild (rerun npm start) after changing this.

I will be adding a section in the admin panel to do this via the webUI, most likely in v2 (React Rewrite)
